services:

  nats:
    image: nats:2.10.22
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -m 8222 --jetstream --store_dir /mnt/jetstream -config /mnt/nats.conf
    networks:
      - hermes-example-pubsub 
    volumes:
      - ./nats/nats.conf:/mnt/nats.conf
      - nats_jetstream_data:/mnt/jetstream

volumes:
  nats_jetstream_data:

networks:
  hermes-example-pubsub:
